# Generated by Django 2.2.4 on 2019-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('domicilio_real', models.CharField(max_length=200)),
                ('domicilio_obra', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=200)),
                ('fecha_alta_cliente', models.DateTimeField(verbose_name='Fecha de alta de cliente')),
                ('fecha_inicio_obra', models.DateTimeField(verbose_name='Fecha de inicio de obra')),
                ('fecha_fin_obra', models.DateTimeField(verbose_name='Fecha de fin de obra')),
            ],
        ),
    ]
