# Generated by Django 2.2.4 on 2019-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqumhome', '0002_auto_20191217_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta_cliente',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_fin_obra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio_obra',
            field=models.DateField(),
        ),
    ]
