# Generated by Django 2.2.4 on 2019-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqumhome', '0004_auto_20191223_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_fin_obra',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio_obra',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
