# Generated by Django 2.2.4 on 2020-01-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arqumhome', '0006_infoperfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoperfilusuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
